#---------------SpringCloud Alibaba下的nacos要求基础配置文件名称bootstrap.properties，所以该文本暂时没用--------------


#server:
#  port: 9102
#spring:
#  application:
#    name: gateway
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: e68d1779-7552-476e-8c19-e4679ef4ea4f
#      config:
#        namespace: e68d1779-7552-476e-8c19-e4679ef4ea4f
#        file-extension: yaml
#        prefix: gateway
#        refresh-enabled: true
#        server-addr: localhost:8848
#    gateway:
#      discovery:
#        locator:
#          #表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
#          lowerCaseServiceId: true
#          #表示gateway开启服务注册和发现功能,
#          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
#          enabled: true
#      httpclient:
#        response-timeout: 5000
#        connect-timeout: 5000
#      routes:
#        - id: nocos-provider
#          uri: lb://nocos-provider #代表从注册中心获取服务，且以lb（负载均衡）的方式转发
#          predicates: #断言
#            - Path=/myprovider/**     #表示将以/provider/**开头的请求转发到uri为lb://nacos-server的地址上
#          filters:
#            - StripPrefix=1 #1为去掉path的/nocos-provider